export const primaryColor = '#155263';
export const secondaryColor = '#fce850';
export const linkColor = "#a52f57";

export const navbarBeforeScrolling = {
    'navbarBgColor': 'transparent',
    'navbarHeight': '40px',
    'bgPrimaryColor': primaryColor,
    'bgSecondaryColor': secondaryColor,
    'backgroundNavbarDropdownContentInMegaDropdown': secondaryColor,
    'colorDropdownNavLink': secondaryColor,
    'color': primaryColor,
    'borderRadius': '100% 10% / 40% 20%',
    'borderRadiusNavbarDropdownContentInMegaDropdown': '360px',
    'borderRadiusNavbarDropdownDivBefore': '360% 360% 360% 360%',
    'borderRadiusNavbarDropdownDivAfter': '360% 360% 360% 360%',
    'displayDiv': 'block',
    'backgroundClip': 'content-box',
    'boxShadow': `0 1px 8px ${primaryColor}`,
    'boxShadowOnHover': `0 1px 16px ${primaryColor}`,
    'navbarBoxShadow': `0 ${primaryColor}`,
    'navbarButtonHeight': '60px',
    'navbarButtonMargin': '0 3px',
    'navbarButtonPadding': '10px 10px 10px 20px',
    'paddingDropdownNavLink': '10px 10px 10px 20px',
    'fontWeightBold': 'bold',
    'borderDoublePrimary': `8px double ${primaryColor}`,
    'borderSolidPrimary': `3px solid ${primaryColor}`,
    'borderDoubleSecondary': `8px double ${secondaryColor}`,
    'borderSolidSecondary': `3px solid ${secondaryColor}`,
    'borderDropdownNavLink': `8px double ${secondaryColor}`,
    'borderSolidDropdownNavLink': `3px solid ${primaryColor}`,
    'borderHoverDropdownNavLink': `8px double ${primaryColor}`,
    'fontFamily': 'Cambria',
    'fontSize': '18px',
    'LogoFontSize': '24px',
    'LogoSize': '44px',
    'navbarIconSize': '22px',
    'navbarIconMarginLeft': '-80px',
    'navbarMenuIconMarginLeft': '-90px',
    'navbarIconMarginBottom': '-45px',
    'navbarButtonWidth': '80px',
    'megaMenuBackground': `linear-gradient(-30deg, ${secondaryColor}, ${primaryColor})`,
    'searchTop': '10px',
    'searchBorderRadius': '20px 10px 20px 10px',
    'searchBoxShadow': `0 1px 8px ${primaryColor}`,
    'searchWidth': '90%',
    'searchMarginLeft': '5%',
    'searchMarginRight': '5%',
    'navbarTop': '50px',
    'marginTopNavbarDropdown': '0',
    'flexGap': '0',
    'primaryColorBeforeSecondaryAfter': primaryColor,
    'primaryColorBeforeTransparentAfter': primaryColor,
    'secondaryColorBeforeTransparentAfter': secondaryColor,
    'paddingTopNavbarDropdownContent': '0',
    'NavbarDropdownListWrapperAfterTop': '199px',
    'NavbarDropdownListWrapperAfterRight': '-6px',
    'NavbarDropdownListWrapperBeforeLeft': '-6px',
}

export const navbarAfterScrolling = {
    'navbarBgColor': primaryColor,
    'navbarHeight': '60px',
    'bgPrimaryColor': 'transparent',
    'bgSecondaryColor': secondaryColor,
    'backgroundNavbarDropdownContentInMegaDropdown': 'transparent',
    'colorDropdownNavLink': primaryColor,
    'color': primaryColor,
    'borderRadius': '5px',
    'borderRadiusNavbarDropdownContentInMegaDropdown': '5px',
    'borderRadiusNavbarDropdownDivBefore': '360% 360% 360% 0',
    'borderRadiusNavbarDropdownDivAfter': '360% 360% 0 360%',
    'displayDiv': 'none',
    'backgroundClip': '',
    'boxShadow': `0 ${primaryColor}`,
    'boxShadowOnHover': `0 ${secondaryColor}`,
    'navbarBoxShadow': `0 1px 8px ${primaryColor}`,
    'navbarButtonHeight': '.8rem',
    'navbarButtonMargin': '0 3px',
    'navbarButtonPadding': '10px 10px 10px 20px',
    'paddingDropdownNavLink': '10px',
    'fontWeightBold': 'bold',
    'borderDoublePrimary': `4px double ${primaryColor}`,
    'borderSolidPrimary': `3px solid ${primaryColor}`,
    'borderDoubleSecondary': `4px double ${secondaryColor}`,
    'borderSolidSecondary': `3px solid ${secondaryColor}`,
    'borderDropdownNavLink': `1px solid ${primaryColor}`,
    'borderHoverDropdownNavLink': `1px solid ${primaryColor}`,
    'borderSolidDropdownNavLink': `1px solid ${primaryColor}`,
    'fontFamily': 'Cambria',
    'fontSize': '18px',
    'LogoFontSize': '24px',
    'LogoSize': '26px',
    'navbarIconSize': '22px',
    'navbarIconMarginLeft': '-80px',
    'navbarMenuIconMarginLeft': '-90px',
    'navbarIconMarginBottom': '0',
    'navbarButtonWidth': '80px',
    'megaMenuBackground': `linear-gradient(-30deg, ${linkColor}, ${secondaryColor})`,
    'searchTop': '0',
    'searchBorderRadius': '0',
    'searchBoxShadow': `0 ${primaryColor}`,
    'searchWidth': '100%',
    'searchMarginLeft': '0',
    'searchMarginRight': '0',
    'navbarTop': '40px',
    'marginTopNavbarDropdown': '20px',
    'flexGap': '3%',
    'primaryColorBeforeSecondaryAfter': secondaryColor,
    'primaryColorBeforeTransparentAfter': 'transparent',
    'secondaryColorBeforeTransparentAfter': 'transparent',
    'paddingTopNavbarDropdownContent': '16px',
    'NavbarDropdownListWrapperAfterTop': '215px',
    'NavbarDropdownListWrapperAfterRight': '-25px',
    'NavbarDropdownListWrapperBeforeLeft': '-25px',
}